FROM rust:1.96-alpine AS chef
WORKDIR /build
RUN cargo install cargo-chef

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
RUN apk add --no-cache \
    musl-dev \
    libseccomp-dev \
    libseccomp-static \
    linux-headers

COPY --from=planner /build/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json --bin agent

COPY . .
RUN cargo build --release --bin agent

FROM alpine:3.23.4

RUN apk add --no-cache libseccomp g++ ccache && \
    rm -rf /var/cache/apk/*

RUN mkdir -p /work /run/judge-core/agents

COPY --from=builder /build/target/release/agent /usr/local/bin/agent

USER root

ENTRYPOINT ["/usr/local/bin/agent"]
